### ISSUE TITLE
Error getting config

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/nodejs-configmap-redhat#72]
Got an error message affter run `npm start`

```console
$ npm start

> nodejs-configmap-redhat@1.4.0 start /home/hf/Documents/nodeshift_starters/nodejs-configmap-redhat
> node .

[winston] Attempt to write logs with no transports {"level":"error","message":"Error getting configThe \"path\" argument must be one of type string, Buffer, or URL. Received type undefined","stack":"TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be one of type string, Buffer, or URL. Received type undefined\n    at readFile (fs.js:302:10)\n    at internal/util.js:286:30\n    at new Promise (<anonymous>)\n    at readFile (internal/util.js:285:12)\n    at retrieveConfigfMap (/home/hf/Documents/nodeshift_starters/nodejs-configmap-redhat/app.js:90:10)\n    at Timeout._onTimeout (/home/hf/Documents/nodeshift_starters/nodejs-configmap-redhat/app.js:63:3)\n    at listOnTimeout (internal/timers.js:531:17)\n    at processTimers (internal/timers.js:475:7)"}
```

**Comment by helio-frota** [comment]
similar
https://github.com/nodeshift-starters/nodejs-configmap/issues/90#issuecomment-513176631
